# HW2：线性代数的基本实现

*大学生科技协会  AI&数模部*

目标：对应 `linear-algebra.ipynb` 中的主要概念（向量、矩阵、按维聚合、点积、矩阵与向量/矩阵相乘、范数等）。前半部分为「补全 TODO」练习；后半部分为**综合题**（给出数据，自行写完整代码，如 softmax 等），各题配有说明。运行后用打印结果做肉眼检查。


In [1]:
import torch

torch.manual_seed(0)


## 1) 向量：分量、长度

向量用一维张量表示。你需要按文字说明取出某个分量，并得到向量包含的元素个数。


In [ ]:
x = torch.tensor([2.0, 0.0, 2.0, 1.0, -1.0])

# 本题约定：要取的分量下标为 2（从 0 开始计数）
# TODO: 取出该下标对应的分量


# TODO: 得到该向量的长度（元素个数）


print("elem:", elem)
print("length:", n)


elem: tensor(2.)
length: 5


## 2) 矩阵：行、全体求和

矩阵用二维张量表示。下面矩阵为 3 行 4 列，元素按行优先排列。


In [ ]:
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)

# TODO: 取出下标为 1 的那一行（仍为向量）


# TODO: 对矩阵中所有元素求和，得到一个标量


print("A:\n", A)
print("row:", row)
print("total:", total)


A:
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
row: tensor([4., 5., 6., 7.])
total: tensor(66.)


## 3) 标量与张量：按元素缩放

标量与张量做运算时，通常按广播规则作用到每个元素上。


In [ ]:
c = 2.5
X = torch.ones(2, 3, dtype=torch.float32)

# TODO: 得到「每个元素都乘以 c」的结果张量


print("Y:\n", Y)
print("Y.shape:", None if Y is None else Y.shape)


Y:
 tensor([[2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000]])
Y.shape: torch.Size([2, 3])


## 4) 降维：按维求和

对矩阵可以「沿某一维」把元素加起来，从而去掉该维。下面矩阵为 4 行 5 列。


In [ ]:
M = torch.arange(20, dtype=torch.float32).reshape(4, 5)

# TODO: 沿「行」这一维求和，使结果长度为 5（即对每一列求和）


# TODO: 沿「列」这一维求和，使结果长度为 4（即对每一行求和）


print("M.shape:", M.shape)
print("sum_over_rows:", sum_over_rows)
print("sum_over_cols:", sum_over_cols)


M.shape: torch.Size([4, 5])
sum_over_rows: tensor([30., 34., 38., 42., 46.])
sum_over_cols: tensor([10., 35., 60., 85.])


## 5) 点积

两个长度相同的向量，对应位置相乘再相加，得到一个标量。


In [ ]:
u = torch.tensor([1.0, 2.0, 3.0, 0.5])
v = torch.tensor([0.0, -1.0, 1.0, 2.0])

# TODO: 计算 u 与 v 的点积（标量）


print("dot:", d)


dot: tensor(2.)


## 6) 矩阵–向量积

矩阵的列数需与向量长度一致；结果是长度等于矩阵行数的向量。


In [ ]:
A = torch.tensor([[1.0, 2.0], [3.0, 4.0], [0.0, -1.0]])
x = torch.tensor([1.0, -1.0])

# TODO: 计算 A 与 x 的矩阵–向量积


print("A.shape:", A.shape, "x.shape:", x.shape)
print("y:", y)


A.shape: torch.Size([3, 2]) x.shape: torch.Size([2])
y: tensor([-1., -1.,  1.])


## 7) 矩阵–矩阵乘法

第一个矩阵的列数需等于第二个矩阵的行数；结果形状为（前者的行数，后者的列数）。不要与逐元素相乘混淆。


In [ ]:
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
B = torch.tensor([[0.0, 1.0], [1.0, 0.0]])

# TODO: 计算 A 与 B 的矩阵乘积


print("C:\n", C)
print("C.shape:", None if C is None else C.shape)


C:
 tensor([[2., 1.],
        [4., 3.]])
C.shape: torch.Size([2, 2])


## 8) 范数（向量长度）

常用欧几里得长度：各分量平方和再开方。


In [ ]:
w = torch.tensor([3.0, 4.0])

# TODO: 计算 w 的 L2 范数（一个标量）


print("L2:", r)


L2: tensor(5.)


## 综合题

下面几题是**综合题**：题目会给出具体张量，请你**自行编写完整代码**完成指定运算。


### 综合题 1：Softmax（一维）

**定义**：对向量 $\mathbf{z} \in \mathbb{R}^d$，其 softmax 的第 $i$ 个分量为

$$\mathrm{softmax}(\mathbf{z})_i = \frac{\exp(z_i)}{\sum_{j=1}^{d} \exp(z_j)}.$$

**直观**：先把每个分量取指数，再除以「全体指数之和」，因此结果**非负**，且**所有分量之和为 1**，可看成在 $d$ 个类别上的概率分布。

**数值稳定**：指数容易溢出。常用技巧是先减去 $m = \max_k z_k$（对全体分量相同），即计算 $\mathrm{softmax}(\mathbf{z}) = \mathrm{softmax}(\mathbf{z} - m\mathbf{1})$，其中 $\mathbf{1}$ 为全 1 向量。因为 softmax 对「整体加常数」不变，这样 $\exp(z_i-m)$ 最大不超过 1。

**在代码里**：对应「按元素指数」「对分量求和得到标量」「用广播把和除到每个分量上」。请**不要**直接调用现成的 softmax 完成本题主体（最后可自行用库函数核对）。


In [ ]:
z = torch.tensor([2.0, 1.0, 0.1, -5.0], dtype=torch.float32)

# 请在此实现：数值稳定的 softmax(z)，结果命名为 p，形状与 z 相同




print("p:", p)
if p is not None:
    print("分量之和（应接近 1）:", p.sum())
# 如需核对，可用框架自带的 softmax 在同一输入上对比（请自行查阅文档）


### 综合题 2：按行 Softmax（二维）

给定矩阵 $\mathbf{X} \in \mathbb{R}^{n \times d}$，**按行 softmax** 表示：对**每一行**单独做一维 softmax，行与行之间互不影响。第 $i$ 行得到长度 $d$ 的向量，其分量之和为 1。

实现时通常对「行内」求和，并注意广播除法时维度是否对齐。


In [ ]:
X = torch.tensor(
    [
        [1.0, 0.0, 2.0],
        [-1.0, 0.0, 1.0],
    ],
    dtype=torch.float32,
)

# 请实现：按行 softmax，结果 P 与 X 同形状，每一行和为 1


print("P:\n", P)
if P is not None:
    print("每行和:", P.sum(dim=1))
# 如需核对，可用框架自带的按行 softmax 在同一输入上对比（请自行查阅文档)


### 综合题 3：余弦相似度

对非零向量 $\mathbf{u}, \mathbf{v} \in \mathbb{R}^d$，**余弦相似度**定义为

$$\cos(\angle(\mathbf{u}, \mathbf{v})) = \frac{\mathbf{u}^\top \mathbf{v}}{\|\mathbf{u}\|_2 \|\mathbf{v}\|_2},$$

其中 $\mathbf{u}^\top \mathbf{v}$ 是点积（同位置相乘再求和），$\|\cdot\|_2$ 是欧几里得范数（L2 范数）。结果在 $[-1, 1]$ 之间，表示两向量夹角的余弦。

请用点积与范数（或等价张量运算）编程计算，不要使用专门求余弦的现成函数（若有可最后对照）。


In [ ]:
u = torch.tensor([1.0, 2.0, 2.0], dtype=torch.float32)
v = torch.tensor([2.0, 0.0, 1.0], dtype=torch.float32)

# 请计算余弦相似度（标量），命名为 c


print("cosine:", c)


### 综合题 4：仿射变换（矩阵–向量 + 广播）

给定批量数据矩阵 $\mathbf{X} \in \mathbb{R}^{n \times d}$（每行一个样本）、权重向量 $\mathbf{w} \in \mathbb{R}^d$ 与偏置标量 $b$，线性模型

$$\mathbf{y} = \mathbf{X}\mathbf{w} + b\mathbf{1}$$

其中 $\mathbf{y} \in \mathbb{R}^n$，$b\mathbf{1}$ 表示把标量 $b$ 加到每个输出上。$\mathbf{X}\mathbf{w}$ 是矩阵–向量积；加 $b$ 时常用广播。

请编程求 $\mathbf{y}$，并打印形状与数值。


In [ ]:
X = torch.tensor(
    [
        [1.0, 0.0, 2.0],
        [0.0, 1.0, -1.0],
    ],
    dtype=torch.float32,
)
w = torch.tensor([0.5, -1.0, 1.0], dtype=torch.float32)
b = 0.25

# 请计算 y（矩阵–向量积与广播；变量名 y）





print("y:", y)
if y is not None:
    print("y.shape:", y.shape)
